function [fitresult, gof] = createFit(new_SOC, R)
%CREATEFIT(NEW_SOC,R)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : new_SOC
%      Y Output: R
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jan-2023 08:11:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( new_SOC, R );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999868094593232;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'R vs. new_SOC', 'SOC-Resistance curve', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'new_SOC', 'Interpreter', 'none' );
ylabel( 'R', 'Interpreter', 'none' );
grid on


